version: '3.10'
services:
  web:
    build:
      dockerfile: Dockerfile
    command: gunicorn family_context.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./:/code
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:alpine
    ports:
      - "${SQL_PORT}:${SQL_PORT}"
    expose:
      - "${SQL_PORT}"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    command: "-p ${SQL_PORT}"
    env_file:
      - ./.env