# Generated by Django 4.1.2 on 2022-10-31 16:27

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=20)),
                (
                    "otherFields",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("lastSynchronised", models.DateTimeField()),
                ("coverageStartDate", models.DateField()),
                ("coverageEndDate", models.DateField()),
                ("dataSource", models.CharField(max_length=70)),
                ("recordsAvailable", models.BooleanField()),
                ("coverageExplanation", models.CharField(max_length=70)),
                (
                    "otherFields",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startDateOfLastInvolvement", models.DateField()),
                ("dateOfMostRecentInteraction", models.DateField()),
                ("DateCurrentAsOf", models.DateField()),
                ("coverageStartDate", models.DateField()),
                ("coverageEndDate", models.DateField()),
                (
                    "serviceInvolvement",
                    models.CharField(
                        choices=[
                            ("Current", "Current"),
                            ("Historic", "Historic"),
                            ("Not Specified", "Not Specified"),
                        ],
                        default="Not Specified",
                        max_length=15,
                    ),
                ),
                ("schoolName", models.CharField(max_length=100)),
                ("contactNumber", models.CharField(max_length=20)),
                ("admissionType", models.CharField(max_length=50)),
                ("coverageGeographicArea", models.DateField()),
                (
                    "otherFields",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.person"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Police",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policeArea", models.CharField(max_length=50)),
                (
                    "otherFields",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.contact"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationType",
                    models.CharField(
                        choices=[
                            ("Sibling", "Sibling"),
                            ("Parent", "Parent"),
                            ("Child", "Child"),
                            ("Grandparent", "Grandparent"),
                            ("Other", "Other"),
                            ("Not Specified", "Not Specified"),
                        ],
                        default="Not Specified",
                        max_length=15,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships",
                        to="core.person",
                    ),
                ),
                (
                    "relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_relationships",
                        to="core.person",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="relation",
            field=models.ManyToManyField(
                through="core.PersonRelationship", to="core.person"
            ),
        ),
        migrations.CreateModel(
            name="OffenceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateOfOffence", models.DateField()),
                ("typeOfOffence", models.CharField(max_length=70)),
                ("natureOfInvolvement", models.CharField(max_length=70)),
                (
                    "otherFields",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "police",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safeguardingOffences",
                        to="core.police",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OffenceRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "otherFields",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "police",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nonSafeGuardingOffences",
                        to="core.police",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Housing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startDateOfLastInvolvement", models.DateField()),
                ("dateOfMostRecentInteraction", models.DateField()),
                ("DateCurrentAsOf", models.DateField()),
                ("coverageStartDate", models.DateField()),
                ("coverageEndDate", models.DateField()),
                (
                    "serviceInvolvement",
                    models.CharField(
                        choices=[
                            ("Current", "Current"),
                            ("Historic", "Historic"),
                            ("Not Specified", "Not Specified"),
                        ],
                        default="Not Specified",
                        max_length=15,
                    ),
                ),
                ("housingAssociation", models.CharField(max_length=100)),
                ("tenancyStart", models.DateField()),
                ("antiSocialBehaviour", models.BooleanField(default=False)),
                ("rentArrears", models.BooleanField(default=False)),
                ("noticeSeekingPossession", models.BooleanField(default=False)),
                ("eviction", models.BooleanField(default=False)),
                ("coverageGeographicArea", models.CharField(max_length=100)),
                (
                    "otherFields",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.contact"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.person"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AdultSocialCare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startDateOfLastInvolvement", models.DateField()),
                ("dateOfMostRecentInteraction", models.DateField()),
                ("DateCurrentAsOf", models.DateField()),
                ("coverageStartDate", models.DateField()),
                ("coverageEndDate", models.DateField()),
                (
                    "serviceInvolvement",
                    models.CharField(
                        choices=[
                            ("Current", "Current"),
                            ("Historic", "Historic"),
                            ("Not Specified", "Not Specified"),
                        ],
                        default="Not Specified",
                        max_length=15,
                    ),
                ),
                ("localAuthorityOrganisation", models.CharField(max_length=50)),
                ("coverageGeographicArea", models.CharField(max_length=70)),
                (
                    "otherFields",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contactFor",
                        to="core.contact",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.person"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
