# Generated by Django 4.1.2 on 2022-11-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_trigram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="coverage_geographic_area",
            field=models.CharField(max_length=100),
        ),
    ]
