# Generated by Django 4.1.2 on 2022-11-09 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_school_coverage_geographic_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesummary",
            name="person",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_summary",
                to="core.person",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="adultsocialcare",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adult_social_care",
                to="core.person",
            ),
        ),
        migrations.AlterField(
            model_name="housing",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="housing",
                to="core.person",
            ),
        ),
        migrations.AlterField(
            model_name="police",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="police",
                to="core.person",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school",
                to="core.person",
            ),
        ),
    ]
