# Generated by Django 4.1.2 on 2022-11-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_servicesummary_person_alter_adultsocialcare_person_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicesummary",
            name="person",
        ),
    ]
