# Generated by Django 4.1.2 on 2022-11-11 22:36

from django.db import migrations, models
import django.db.models.deletion


def set_default_service_to_school(apps, schema_editor):
    service = apps.get_model("core", "ServiceSummary")
    school = apps.get_model("core", "School")
    school.objects.update(service=service.objects.first())


def revert_set_default_service_to_school(apps, schema_editor):
    school = apps.get_model("core", "School")
    school.objects.update(service=None)


def set_default_service_to_police(apps, schema_editor):
    service = apps.get_model("core", "ServiceSummary")
    police = apps.get_model("core", "Police")
    police.objects.update(service=service.objects.first())


def revert_set_default_service_to_police(apps, schema_editor):
    police = apps.get_model("core", "Police")
    police.objects.update(service=None)


def set_default_service_to_housing(apps, schema_editor):
    service = apps.get_model("core", "ServiceSummary")
    housing = apps.get_model("core", "Housing")
    housing.objects.update(service=service.objects.first())


def revert_set_default_service_to_housing(apps, schema_editor):
    housing = apps.get_model("core", "Housing")
    housing.objects.update(service=None)


def set_default_service_to_adsc(apps, schema_editor):
    service = apps.get_model("core", "ServiceSummary")
    adsc = apps.get_model("core", "AdultSocialCare")
    adsc.objects.update(service=service.objects.first())


def revert_set_default_service_to_adsc(apps, schema_editor):
    adsc = apps.get_model("core", "AdultSocialCare")
    adsc.objects.update(service=None)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_servicesummary_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="adultsocialcare",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_adult_social_care_records",
                to="core.servicesummary",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_service_to_adsc, reverse_code=revert_set_default_service_to_adsc),
        migrations.AlterField(
            model_name="adultsocialcare",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_adult_social_care_records",
                to="core.servicesummary",
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name="police",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_police_records",
                to="core.servicesummary",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_service_to_police, reverse_code=revert_set_default_service_to_police),
        migrations.AlterField(
            model_name="police",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_police_records",
                to="core.servicesummary",
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name="housing",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_housing_records",
                to="core.servicesummary",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_service_to_housing, reverse_code=revert_set_default_service_to_housing),
        migrations.AlterField(
            model_name="housing",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_housing_records",
                to="core.servicesummary",
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name="school",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_school_records",
                to="core.servicesummary",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_service_to_school, reverse_code=revert_set_default_service_to_school),
        migrations.AlterField(
            model_name="school",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_school_records",
                to="core.servicesummary",
            ),
            preserve_default=False,
        ),

    ]
